{
 "title": "IoT Copy",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Rss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rss\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"val\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rss\")\n  |> aggregateWindow(every: 3m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aqi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"aqi\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"val\")\n  |> aggregateWindow(every: 3m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"gas\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"val\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gas\" or r[\"_field\"] == \"gasPred\")\n  |> filter(fn: (r) => r[\"clientId\"] == \"diubi-esp-32\")\n  |> filter(fn: (r) => r[\"lat\"] == \"42.846290\" or r[\"lat\"] == \"999\")\n  |> aggregateWindow(every: 3m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"humidity\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"val\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"clientId\"] == \"diubi-esp-32\")\n  |> filter(fn: (r) => r[\"lat\"] == \"42.846290\" or r[\"lat\"] == \"999\")\n  |> aggregateWindow(every: 3m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"temperature\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"val\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"clientId\"] == \"diubi-esp-32\")\n  |> filter(fn: (r) => r[\"lat\"] == \"42.846290\" or r[\"lat\"] == \"999\")\n  |> aggregateWindow(every: 3m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}